name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.11']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: '5.7'
          mysql root password: ${{ secrets.ADMIN_DB_PASSWORD }}
          mysql database: 'epicevents'
          host port: '3306'
          container port: '3306'

      - name: Wait for MySQL to be ready
        run: |
          for i in {30..0}; do
            if docker exec mysql mysqladmin ping -h "localhost" --silent; then
              break
            fi
            echo 'MySQL still not ready, sleeping...'
            sleep 1
          done

      - name: Install dependencies on Ubuntu and macOS
        if: runner.os != 'windows-latest'
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install

      - name: Install dependencies on Windows
        if: runner.os == 'windows-latest'
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install

      - name: Create .env file from secret
        run: |
          echo -e "${{ secrets.ENV_FILE }}" > .env
          cat .env

      - name: Show help for application
        run: |
          pipenv run python epicevents/main.py --help

      - name: Run tests on Ubuntu and macOS
        if: runner.os != 'windows-latest'
        run: |
          pipenv run pytest -v tests/

      - name: Run tests on Windows
        if: runner.os == 'windows-latest'
        run: |
          pipenv run pytest -v tests/
